@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Student as student
participant MakeCourseEnrollmentApplicationUI as MakeCourseEnrollmentApplicationUI <<presentation>>
participant OpenEnrollmentCoursesAvailableToEnrollStudentSessionService as OpenEnrollmentCoursesAvailableToEnrollStudentSessionService <<application>>
participant ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService as ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService <<domain>>
participant FindStudentByUsernameService as FindStudentByUsernameService <<application>>
participant FindCourseByCourseCodeService as FindCourseByCourseCodeService <<application>>
participant CreateCourseEnrollmentController as CreateCourseEnrollmentController <<application>>
participant CourseEnrollmentBuilder as CourseEnrollmentBuilder <<builder>>
participant CourseEnrollment as CourseEnrollment <<domain>>
database StudentRepository as StudentRepository <<persistence>>
database CourseRepository as CourseRepository <<persistence>>
database CourseEnrollmentRepository as CourseEnrollmentRepository <<persistence>>

activate student
student->MakeCourseEnrollmentApplicationUI : asks to enroll in a course
deactivate student
activate MakeCourseEnrollmentApplicationUI
MakeCourseEnrollmentApplicationUI->OpenEnrollmentCoursesAvailableToEnrollStudentSessionService : list open enrollment courses that student isn't already candidate/enrolled
deactivate MakeCourseEnrollmentApplicationUI
activate OpenEnrollmentCoursesAvailableToEnrollStudentSessionService
OpenEnrollmentCoursesAvailableToEnrollStudentSessionService->ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService : list open enrollment courses that student isn't already candidate/enrolled
deactivate OpenEnrollmentCoursesAvailableToEnrollStudentSessionService
activate ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService
ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService->CourseRepository : list open enrollment courses
deactivate ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService
activate CourseRepository
CourseRepository->ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService : returns open enrollment courses
deactivate CourseRepository
activate ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService
ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService->StudentRepository : find student by username
deactivate ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService
activate StudentRepository
StudentRepository->ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService : returns student
deactivate StudentRepository
activate ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService
ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService->CourseRepository : find courses by their code
deactivate ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService
activate CourseRepository
CourseRepository->ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService : returns courses
deactivate CourseRepository
activate ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService
ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService->CourseEnrollmentRepository : find courses student is enrolled
deactivate ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService
activate CourseEnrollmentRepository
CourseEnrollmentRepository->ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService : returns courses
deactivate CourseEnrollmentRepository
activate ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService
ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService->OpenEnrollmentCoursesAvailableToEnrollStudentSessionService : returns open enrollment courses that student isn't already candidate/enrolled
deactivate ListOpenEnrollmentCoursesAvailableToEnrollStudentSessionService
activate OpenEnrollmentCoursesAvailableToEnrollStudentSessionService
OpenEnrollmentCoursesAvailableToEnrollStudentSessionService->MakeCourseEnrollmentApplicationUI : returns open enrollment courses that student isn't already candidate/enrolled
deactivate OpenEnrollmentCoursesAvailableToEnrollStudentSessionService
activate MakeCourseEnrollmentApplicationUI
MakeCourseEnrollmentApplicationUI->student : asks course to enroll
deactivate MakeCourseEnrollmentApplicationUI
activate student
student->MakeCourseEnrollmentApplicationUI : selects course to enroll
deactivate student
activate MakeCourseEnrollmentApplicationUI
MakeCourseEnrollmentApplicationUI->CreateCourseEnrollmentController : create a course enrollment
deactivate MakeCourseEnrollmentApplicationUI
activate CreateCourseEnrollmentController
CreateCourseEnrollmentController->FindStudentByUsernameService : find student by username
deactivate CreateCourseEnrollmentController
activate FindStudentByUsernameService
FindStudentByUsernameService->StudentRepository : gets student
deactivate FindStudentByUsernameService
activate StudentRepository
StudentRepository->FindStudentByUsernameService : returns student
deactivate StudentRepository
activate FindStudentByUsernameService
FindStudentByUsernameService->CreateCourseEnrollmentController : returns student
deactivate FindStudentByUsernameService
activate CreateCourseEnrollmentController
CreateCourseEnrollmentController->FindCourseByCourseCodeService : find course by course code
deactivate CreateCourseEnrollmentController
activate FindCourseByCourseCodeService
FindCourseByCourseCodeService->CourseRepository : gets course
deactivate FindCourseByCourseCodeService
activate CourseRepository
CourseRepository->FindCourseByCourseCodeService : returns course
deactivate CourseRepository
activate FindCourseByCourseCodeService
FindCourseByCourseCodeService->CreateCourseEnrollmentController : returns course
deactivate FindCourseByCourseCodeService
activate CreateCourseEnrollmentController
CreateCourseEnrollmentController->CourseEnrollmentBuilder : create course enrollment
deactivate CreateCourseEnrollmentController
activate CourseEnrollmentBuilder
CourseEnrollmentBuilder->CourseEnrollment : build course enrollment
deactivate CourseEnrollmentBuilder
activate CourseEnrollment
CourseEnrollment->CourseEnrollmentBuilder : returns course enrollment
deactivate CourseEnrollment
activate CourseEnrollmentBuilder
CourseEnrollmentBuilder->CreateCourseEnrollmentController : returns course enrollment
deactivate CourseEnrollmentBuilder
activate CreateCourseEnrollmentController
CreateCourseEnrollmentController->CourseEnrollmentRepository : save course enrollment
deactivate CreateCourseEnrollmentController
activate CourseEnrollmentRepository
CourseEnrollmentRepository->CreateCourseEnrollmentController : returns course enrollment
deactivate CourseEnrollmentRepository
activate CreateCourseEnrollmentController
CreateCourseEnrollmentController->MakeCourseEnrollmentApplicationUI : returns course enrollment
deactivate CreateCourseEnrollmentController
activate MakeCourseEnrollmentApplicationUI
MakeCourseEnrollmentApplicationUI->student : shows message of successful/failure enrollment creation
deactivate MakeCourseEnrollmentApplicationUI


@enduml